# Generated by Django 4.0 on 2021-12-29 19:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(blank=True, db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=256, unique=True, verbose_name='subject')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'newsroom"."news',
            },
        ),
    ]
